name: first workflow experience

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List and Read file
        run: |
          echo "Welcome to the first workflow experience"
          ls -ltra
          cat README.md

      - name: Generate ASCII Art
        run: cowsay -f dragon "Run for cover, i am a DRAGON....RAWR" >> dragon.txt

      # - name: List files
      #   run: ls -a

      # - name: Read file
      #   run: cat README.md
