name: Generate ASCII Artwork

on: push

jobs:
  ascii_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cowsay package
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, i am a DRAGON....RAWR" >> dragon.txt

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: Checkout Repo Files
        run: ls
      # - name: List files
      #   run: ls -a

      # - name: Read file
      #   run: cat README.md
