name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: actions/checkout@v4

      - name: Install Cowsay package
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a Dragon....RAAR" >> dragon.txt

      - name: Sleep for 30 seconds
        run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 10

      - name: Test file Exists
        run: grep -i "dragon" dragon.txt

  deploy_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ... .. ..
