name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay package
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a Dragon....RAAR" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt

      - name: Check if dragon.txt is a file
        run: |
          if [ -f dragon.txt ]; then
            echo "dragon.txt is a file"
          else
            echo "Error: dragon.txt is not a file"
            exit 1
          fi

      - name: Test file Exists
        run: grep -i "dragon" dragon.txt

  deploy_job_2:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt

      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying ... .. ..
