name: Exploring Variables and Secrets

on: 
    push

jobs:
    docker:
     runs-on: ubuntu-latest
     steps: 
        - name: Docker Build
          env: 
            CONTAINER_REGISTRY: docker.io
            Docker_USERNAME: sideharth1
            IMAGE_NAME: github-actions-nginx
          run: echo docker build -t {{ env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
         
        - name: Docker Login
          env: 
            DOCKER_USERNAME: sideharth1
            Docker_PASSWORD: s3cUrePaSsword
          run: echo docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          env: 
            CONTAINER_REGISTRY: docker.io
            Docker_USERNAME: sideharth1
            IMAGE_NAME: github-actions-nginx
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
      needs: docker 
      runs-on: ubuntu-latest
      steps: 
        - name: Docker Run
          run: echo docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest
